export const gallery = [
  {
    labelEn: 'Alpina D3',
    labelCs: 'Alpina D3',
    date: '10-04-2024',
    href: '/gallery/alpina-d3',
    slug: 'alpina-d3',
    categories: ['cars'],
    images: [
      '/gallery/alpina-d3/1.webp',
      '/gallery/alpina-d3/2.webp',
      '/gallery/alpina-d3/3.webp',
      '/gallery/alpina-d3/4.webp',
      '/gallery/alpina-d3/5.webp',
      '/gallery/alpina-d3/6.webp',
      '/gallery/alpina-d3/7.webp',
      '/gallery/alpina-d3/8.webp',
      '/gallery/alpina-d3/9.webp',
      '/gallery/alpina-d3/10.webp',
      '/gallery/alpina-d3/11.webp',
      '/gallery/alpina-d3/12.webp',
    ],
  },
  {
    labelEn: 'Uninvited Guest',
    labelCs: 'Nezvaný Host',
    date: '12-04-2024',
    href: '/gallery/peter',
    slug: 'peter',
    categories: ['animals'],
    images: [
      '/gallery/peter/1.webp',
      '/gallery/peter/2.webp',
      '/gallery/peter/3.webp',
      '/gallery/peter/4.webp',
      '/gallery/peter/5.webp',
      '/gallery/peter/6.webp',
      '/gallery/peter/7.webp',
      '/gallery/peter/8.webp',
      '/gallery/peter/9.webp',
    ],
  },
  {
    labelEn: 'Faithful',
    labelCs: 'Věrná',
    date: '21-03-2024',
    href: '/gallery/faithful',
    slug: 'faithful',
    categories: ['cars'],
    images: [
      '/gallery/faithful/1.webp',
      '/gallery/faithful/2.webp',
      '/gallery/faithful/3.webp',
      '/gallery/faithful/4.webp',
      '/gallery/faithful/5.webp',
    ],
  },
  {
    labelEn: 'New Face',
    labelCs: 'Nová Tvář',
    date: '21-03-2024',
    href: '/gallery/g80',
    slug: 'g80',
    categories: ['cars'],
    images: [
      '/gallery/g80/1.webp',
      '/gallery/g80/2.webp',
      '/gallery/g80/3.webp',
      '/gallery/g80/4.webp',
      '/gallery/g80/5.webp',
    ],
  },
  {
    labelEn: 'Demon Time',
    labelCs: 'Doba Démona',
    date: '9-04-2024',
    href: '/gallery/mazda',
    slug: 'mazda',
    categories: ['cars'],
    images: [
      '/gallery/mazda/1.webp',
      '/gallery/mazda/2.webp',
      '/gallery/mazda/3.webp',
      '/gallery/mazda/4.webp',
      '/gallery/mazda/5.webp',
      '/gallery/mazda/6.webp',
    ],
  },
  {
    labelEn: 'Testarossa',
    labelCs: 'Testarossa',
    date: '25-03-2024',
    href: '/gallery/ferrari',
    slug: 'ferrari',
    categories: ['cars'],
    images: [
      '/gallery/ferrari/1.webp',
      '/gallery/ferrari/2.webp',
      '/gallery/ferrari/3.webp',
      '/gallery/ferrari/4.webp',
      '/gallery/ferrari/5.webp',
      '/gallery/ferrari/6.webp',
      '/gallery/ferrari/7.webp',
      '/gallery/ferrari/8.webp',
      '/gallery/ferrari/9.webp',
    ],
  },
  {
    labelEn: 'The Devil in paradise',
    labelCs: 'Ďábel v ráji',
    date: '11-04-2024',
    href: '/gallery/toyota',
    slug: 'toyota',
    categories: ['cars'],
    images: [
      '/gallery/toyota/1.webp',
      '/gallery/toyota/2.webp',
      '/gallery/toyota/3.webp',
      '/gallery/toyota/4.webp',
      '/gallery/toyota/5.webp',
      '/gallery/toyota/6.webp',
      '/gallery/toyota/7.webp',
    ],
  },
]
