export const photography = [
  {
    labelEn: 'Beast in the wrong environment',
    labelCs: 'Šelma v nesprávném prostředí',
    href: '/photography/peter',
    slug: 'peter',
    images: [
      '/photography/peter/1.webp',
      '/photography/peter/2.webp',
      '/photography/peter/3.webp',
      '/photography/peter/4.webp',
      '/photography/peter/5.webp',
      '/photography/peter/6.webp',
      '/photography/peter/7.webp',
      '/photography/peter/8.webp',
      '/photography/peter/9.webp',
    ],
  },
  {
    labelEn: 'Legend in the woods',
    labelCs: 'Legenda v lese',
    href: '/photography/alpina-d3',
    slug: 'alpina-d3',
    images: [
      '/photography/alpina-d3/1.webp',
      '/photography/alpina-d3/2.webp',
      '/photography/alpina-d3/3.webp',
      '/photography/alpina-d3/4.webp',
      '/photography/alpina-d3/5.webp',
      '/photography/alpina-d3/6.webp',
      '/photography/alpina-d3/7.webp',
      '/photography/alpina-d3/8.webp',
      '/photography/alpina-d3/9.webp',
      '/photography/alpina-d3/10.webp',
      '/photography/alpina-d3/11.webp',
      '/photography/alpina-d3/12.webp',
    ],
  },
  {
    labelEn: "Julia's Beast",
    labelCs: 'Juliina Bestie',
    href: '/photography/julia-f30',
    slug: 'julia-f30',
    images: [
      '/photography/julia-f30/1.webp',
      '/photography/julia-f30/2.webp',
      '/photography/julia-f30/3.webp',
      '/photography/julia-f30/4.webp',
      '/photography/julia-f30/5.webp',
    ],
  },
]
