export const photography = [
  {
    labelEn: 'Legend in the woods',
    labelCs: 'Legenda v lese',
    href: '/photography/alpina-d3',
    slug: 'alpina-d3',
    images: [
      '/photography/alpina-d3/1.webp',
      '/photography/alpina-d3/2.webp',
      '/photography/alpina-d3/3.webp',
      '/photography/alpina-d3/4.webp',
      '/photography/alpina-d3/5.webp',
      '/photography/alpina-d3/6.webp',
      '/photography/alpina-d3/7.webp',
      '/photography/alpina-d3/8.webp',
      '/photography/alpina-d3/9.webp',
      '/photography/alpina-d3/10.webp',
      '/photography/alpina-d3/11.webp',
      '/photography/alpina-d3/12.webp',
    ],
  },
  {
    labelEn: 'Impostor',
    labelCs: 'Imitátor',
    href: '/photography/peter',
    slug: 'peter',
    images: [
      '/photography/peter/1.webp',
      '/photography/peter/2.webp',
      '/photography/peter/3.webp',
      '/photography/peter/4.webp',
      '/photography/peter/5.webp',
      '/photography/peter/6.webp',
      '/photography/peter/7.webp',
      '/photography/peter/8.webp',
      '/photography/peter/9.webp',
    ],
  },
  {
    labelEn: "Julia's Beast",
    labelCs: 'Juliina Bestie',
    href: '/photography/julia-f30',
    slug: 'julia-f30',
    images: [
      '/photography/julia-f30/1.webp',
      '/photography/julia-f30/2.webp',
      '/photography/julia-f30/3.webp',
      '/photography/julia-f30/4.webp',
      '/photography/julia-f30/5.webp',
    ],
  },
  {
    labelEn: 'New Face',
    labelCs: 'Nová Tvář',
    href: '/photography/g80',
    slug: 'g80',
    images: [
      '/photography/g80/1.webp',
      '/photography/g80/2.webp',
      '/photography/g80/3.webp',
      '/photography/g80/4.webp',
      '/photography/g80/5.webp',
    ],
  },
  {
    labelEn: 'Night Car Only',
    labelCs: 'Pouze noční vůz',
    href: '/photography/mazda',
    slug: 'mazda',
    images: [
      '/photography/mazda/1.webp',
      '/photography/mazda/2.webp',
      '/photography/mazda/3.webp',
      '/photography/mazda/4.webp',
      '/photography/mazda/5.webp',
      '/photography/mazda/6.webp',
    ],
  },
  {
    labelEn: '10 cylinders is not enough',
    labelCs: '10 válců nestačí',
    href: '/photography/ferrari',
    slug: 'ferrari',
    images: [
      '/photography/ferrari/1.webp',
      '/photography/ferrari/2.webp',
      '/photography/ferrari/3.webp',
      '/photography/ferrari/4.webp',
      '/photography/ferrari/5.webp',
      '/photography/ferrari/6.webp',
      '/photography/ferrari/7.webp',
      '/photography/ferrari/8.webp',
      '/photography/ferrari/9.webp',
    ],
  },
  {
    labelEn: 'Blooming Youngtimer',
    labelCs: 'Kvetoucí Youngtimer',
    href: '/photography/toyota',
    slug: 'toyota',
    images: [
      '/photography/toyota/1.webp',
      '/photography/toyota/2.webp',
      '/photography/toyota/3.webp',
      '/photography/toyota/4.webp',
      '/photography/toyota/5.webp',
      '/photography/toyota/6.webp',
      '/photography/toyota/7.webp',
    ],
  },
]
