export const projects = [
  {
    name: 'Planetopedia',
    slug: 'planetopedia',
    url: 'https://planetopedia.agency',
    href: '/projects/planetopedia',
    year: 2023,
    descriptionEn: 'Marketing digital agency',
    descriptionCs: 'Digitalní marketingová agentura',
    image: '/projects/planetopedia/mockups.webp',
    iphone: '/projects/planetopedia/iphone.webp',
    macbook: '/projects/planetopedia/macbook.webp',
    images: [
      '/projects/planetopedia/1.webp',
      '/projects/planetopedia/2.webp',
      '/projects/planetopedia/3.webp',
      '/projects/planetopedia/4.webp',
      '/projects/planetopedia/5.webp',
      '/projects/planetopedia/6.webp',
      '/projects/planetopedia/7.webp',
    ],
  },
  {
    name: 'Farma Hájek',
    slug: 'farmahajek',
    url: 'https://farmahajek.cz',
    href: '/projects/farmahajek',
    year: 2023,
    descriptionEn: 'Family farm',
    descriptionCs: 'Rodinná farma',
    image: '/projects/farmahajek/mockups.webp',
    iphone: '/projects/farmahajek/iphone.webp',
    macbook: '/projects/farmahajek/macbook.webp',
    images: ['/projects/farmahajek/1.webp'],
  },
  {
    name: 'Pneuservis Baudyš',
    slug: 'pneuservisbaudys',
    url: 'https://pneuservisbaudys.cz',
    href: '/projects/pneuservisbaudys',
    year: 2022,
    descriptionEn: 'Local tyre workshop',
    descriptionCs: 'Lokální pneuservis',
    image: '/projects/pneuservisbaudys/mockups.webp',
    iphone: '/projects/pneuservisbaudys/iphone.webp',
    macbook: '/projects/pneuservisbaudys/macbook.webp',
    images: ['/projects/pneuservisbaudys/1.webp'],
  },
  {
    name: 'Tespra',
    slug: 'tespra',
    url: 'https://tespra.cz',
    href: '/projects/tespra',
    year: 2023,
    descriptionEn: 'Feed shop',
    descriptionCs: 'Obchůdek s krmivem',
    image: '/projects/tespra/mockups.webp',
    iphone: '/projects/tespra/iphone.webp',
    macbook: '/projects/tespra/macbook.webp',
    images: [
      '/projects/tespra/1.webp',
      '/projects/tespra/2.webp',
      '/projects/tespra/3.webp',
    ],
  },
]
