export const projects = [
  {
    name: 'Farma Hájek',
    slug: 'farmahajek',
    url: 'https://farmahajek.cz',
    href: '/projects/farmahajek',
    year: 2023,
    featuresEn: [
      'Feedback form',
      'Embed Google Map',
      'Custom Map',
      'Photo gallery',
    ],
    featuresCs: [
      'Formulář zpětné vazby',
      'Integrovaná mapa Google',
      'Vlastní mapa',
      'Fotogalerie',
    ],
    descriptionEn: 'Family farm',
    descriptionCs: 'Rodinná farma',
    image: '/projects/farmahajek/mockups.webp',
    iphone: '/projects/farmahajek/iphone.webp',
    macbook: '/projects/farmahajek/macbook.webp',
    images: ['/projects/farmahajek/1.webp', '/projects/farmahajek/2.webp'],
  },
  {
    name: 'Rozmluv se',
    slug: 'rozmluvse',
    url: 'https://rozmluv.se',
    href: '/projects/rozmluvse',
    year: 2024,
    featuresEn: ['Blog', 'CMS', 'Animations', 'Admin Dashboard'],
    featuresCs: ['Blog', 'CMS', 'Animace', 'Admin Rozhraní'],
    descriptionEn: 'Language studio',
    descriptionCs: 'Jazykové studio',
    image: '/projects/rozmluvse/mockups.webp',
    iphone: '/projects/rozmluvse/iphone.webp',
    macbook: '/projects/rozmluvse/macbook.webp',
    images: [
      '/projects/rozmluvse/1.webp',
      '/projects/rozmluvse/2.webp',
      '/projects/rozmluvse/3.webp',
      '/projects/rozmluvse/4.webp',
      '/projects/rozmluvse/5.webp',
      '/projects/rozmluvse/6.webp',
      '/projects/rozmluvse/7.webp',
    ],
  },

  {
    name: 'Pneuservis Baudyš',
    slug: 'pneuservisbaudys',
    url: 'https://pneuservisbaudys.cz',
    href: '/projects/pneuservisbaudys',
    year: 2022,

    featuresEn: ['3D model', 'Embed Google Map'],
    featuresCs: ['3D model', 'Integrovaná mapa Google'],
    descriptionEn: 'Local tyre workshop',
    descriptionCs: 'Lokální pneuservis',
    image: '/projects/pneuservisbaudys/mockups.webp',
    iphone: '/projects/pneuservisbaudys/iphone.webp',
    macbook: '/projects/pneuservisbaudys/macbook.webp',
    images: ['/projects/pneuservisbaudys/1.webp'],
  },
  {
    name: 'Dhiffushi Inn',
    slug: 'dhiffushiinn',
    url: 'https://dhiffushi-inn.vercel.app',
    href: '/projects/dhiffushiinn',
    year: 2024,
    featuresEn: [
      'Booking system',
      'Forms',
      'Embed Google Map',
      'Photo gallery',
      'CMS',
    ],
    featuresCs: [
      'Rezervační systém',
      'Formuláře',
      'Integrovaná mapa Google',
      'Fotogalerie',
      'CMS',
    ],
    descriptionEn: 'Maldivian guesthouse',
    descriptionCs: 'Maledivský penzion',
    image: '/projects/dhiffushiinn/mockups.webp',
    iphone: '/projects/dhiffushiinn/iphone.webp',
    macbook: '/projects/dhiffushiinn/macbook.webp',
    images: [
      '/projects/dhiffushiinn/1.webp',
      '/projects/dhiffushiinn/2.webp',
      '/projects/dhiffushiinn/3.webp',
      '/projects/dhiffushiinn/4.webp',
      '/projects/dhiffushiinn/5.webp',
    ],
  },
]
