export const projects = [
  {
    name: 'Planetopedia',
    slug: 'planetopedia',
    url: 'https://planetopedia.agency',
    href: '/projects/planetopedia',
    year: 2023,
    image: '/projects/planetopedia/mockups.webp',
    images: [
      '/projects/planetopedia/1.webp',
      '/projects/planetopedia/2.webp',
      '/projects/planetopedia/3.webp',
      '/projects/planetopedia/4.webp',
      '/projects/planetopedia/5.webp',
      '/projects/planetopedia/6.webp',
      '/projects/planetopedia/7.webp',
    ],
  },
  {
    name: 'Pneuservis Baudyš',
    slug: 'pneuservisbaudys',
    url: 'https://pneuservisbaudys.cz',
    href: '/projects/pneuservisbaudys',
    year: 2022,
    image: '/projects/pneuservisbaudys/mockups.webp',
    images: ['/projects/pneuservisbaudys/1.webp'],
  },
  {
    name: 'Farma Hájek',
    slug: 'farmahajek',
    url: 'https://farmahajek.cz',
    href: '/projects/farmahajek',
    year: 2023,
    image: '/projects/farmahajek/mockups.webp',
    images: ['/projects/farmahajek/1.webp'],
  },
  {
    name: 'Tespra',
    slug: 'tespra',
    url: 'tespra',
    href: 'tespra',
    year: 2023,
    image: '/projects/tespra/mockups.webp',
    images: [
      '/projects/tespra/1.webp',
      '/projects/tespra/2.webp',
      '/projects/tespra/3.webp',
    ],
  },
]
